require 'hoe'
require './lib/rsssf/version.rb'

Hoe.spec 'rsssf' do

  self.version = Rsssf::VERSION

  self.summary = "rsssf - tools 'n' scripts for RSSSF (Rec.Sport.Soccer Statistics Foundation) archive data"
  self.description = summary

  self.urls    = { home: 'https://github.com/rsssf/scripts' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ['season-formats'],
    ['webget'],
  ]


  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
